### PR TITLE
clean up the repository a little bit :3

### PR DESCRIPTION
**Pull request by pauliesnug**
- reformat everything (this is opinionated, i can tweak it if needed)
- stop using webpack (switch to modern node, tsup)
  - decreases build size by so much
  - allows us to stop including `node_modules`, instead we can just inline dependencies (might break something... not sure)
- improve vscode settings, add some tests
- use modern vscode extension standards, (`assets` -> `res`)
- standardize indentation to be a "hard" tab character. this is better for accessibility (https://gomakethings.com/tabs-are-objectively-better-than-spaces/) and fits in with the codebase better. i used `unindent` for the inline html/css code so that should also be standardized.

let me know if i should change anything (or if explainations are needed etc)
the website repo could also be cleaned up a little bit...

### CODE REVIEW

**Comment by matcool** [comment]
why switch to tsup? i dont see it mentioned anywhere in official vscode extension examples. and also can you not format literally every single file in the repo? makes it hard to judge what you actually changed

**Comment by matcool** [comment]
why did you get rid of package-lock.json? are we just forced to use pnpm now?

**Comment by pauliesnug** [comment]
> why did you get rid of package-lock.json? are we just forced to use pnpm now?

no, i can revert it if needed. the pnpm-workspace.yaml was accidental

**Comment by pauliesnug** [comment]
> why switch to tsup? i dont see it mentioned anywhere in official vscode extension examples. and also can you not format literally every single file in the repo? makes it hard to judge what you actually changed

`tsup` is just a cli wrapper for `esbuild`, which is much faster and more efficient when compared to webpack.

**Comment by pauliesnug** [comment]
as for the formatting, i tried to make all the formatting commits into one single commit (the second one). also, github's diff viewer highlights indentation and changes separately, so the changes are apparent (for some reason it doesn't do this with json, but everything else should show the changes...

**Comment by pauliesnug** [comment]
also i noticed the website was already being rewritten, it looks much better

**Comment by matcool** [comment]
> > why switch to tsup? i dont see it mentioned anywhere in official vscode extension examples. and also can you not format literally every single file in the repo? makes it hard to judge what you actually changed
> 
> `tsup` is just a cli wrapper for `esbuild`, which is much faster and more efficient when compared to webpack. it's used in a lot of vscode extensions i've seen, i based it off of https://github.com/antfu/starter-vscode

how big of a difference in build size does it make? and make sure to test the sprite browser since that uses `sharp` and is the most likely to break. if its significant enough i feel like it could be an interesting change but i would prefer it as its own pr, instead of a mega one

**Comment by pauliesnug** [comment]
> how big of a difference in build size does it make? and make sure to test the sprite browser since that uses `sharp` and is the most likely to break. if its significant enough i feel like it could be an interesting change but i would prefer it as its own pr, instead of a mega one

okay! i can try to seperate the buildsystem changes and formatting changes, as they are already in different commits. i'll do some more testing on this and report back in a few hours.

**Comment by pauliesnug** [comment]
as for the difference in build size, it's a little complicated. on it's own, webpack compiles all the code in ~350kb from what I can see. however, once you include all the `"dependencies"` added to the bundle, (461.8kb (and 20.2 mb for sharp, and 1.21 mb for codicons) according to bundlephobia), it comes out to over 22.2218 mb.

tsup on the other hand, is able to compile all code using esbuild, which is proven to be faster and more efficient in compilation than webpack and ts-loader. it is able to take _all_ the code (including all dependencies), and put it into a ~ 700kb index.js file. this means that only the code that we actually need is included, with "treeshaking". this reduces the bundle size significantly (22.2218 mb vs 700 kb)

**Comment by pauliesnug** [comment]
@matcool I fixed some issues, but for some reason the playground isn't detecting my Geode CLI. Could someone else try testing it?

**Pull request closed without merging**
